//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeTimesCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_T
    {
        public long Admin_ID { get; set; }
        public string Admin_Username { get; set; }
        public string Admin_Password { get; set; }
        public string Admin_TureName { get; set; }
        public string Admin_Email { get; set; }
        public string Admin_PhoneNum { get; set; }
        public long Admin_OwerCompanyId { get; set; }
        public int Admin_IsAdmin { get; set; }
    
        public virtual Company_T Company_T { get; set; }
    }
}
