//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeTimesCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Key_T
    {
        public long Key_Id { get; set; }
        public long Key_UserId { get; set; }
        public long Key_QuestionId { get; set; }
        public string Key_Key { get; set; }
    
        public virtual User_T User_T { get; set; }
    }
}
