//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeTimesCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionnarire_T
    {
        public long Questionnaire_Id { get; set; }
        public string Questionnaire_Name { get; set; }
        public long Qusetionnaire_OwerCompany { get; set; }
        public string Questionnaire_Questions { get; set; }
        public System.DateTime Questionnaire_BirthTime { get; set; }
        public System.DateTime Questionnaire_EndTime { get; set; }
        public System.DateTime Questionnarire_StartTime { get; set; }
    
        public virtual Company_T Company_T { get; set; }
    }
}
