//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeTimesCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question_T
    {
        public long Question_Id { get; set; }
        public string Question_Title { get; set; }
        public int Question_Class { get; set; }
        public string Question_Option1 { get; set; }
        public string Question_Option2 { get; set; }
        public string Question_Option3 { get; set; }
        public string Question_Option4 { get; set; }
        public string Question_Option5 { get; set; }
        public string Question_Option6 { get; set; }
        public string Question_Option7 { get; set; }
    
        public virtual QuestionClass_T QuestionClass_T { get; set; }
    }
}
