//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeTimesCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_T
    {
        public User_T()
        {
            this.Key_T = new HashSet<Key_T>();
        }
    
        public long User_Id { get; set; }
        public string User_TrueName { get; set; }
        public long User_OwerCompanyId { get; set; }
        public string User_Department { get; set; }
        public string User_Email { get; set; }
        public string User_Username { get; set; }
        public string User_Password { get; set; }
        public int User_State { get; set; }
    
        public virtual Company_T Company_T { get; set; }
        public virtual ICollection<Key_T> Key_T { get; set; }
    }
}
