//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public long admin_Id { get; set; }
        public string admin_Username { get; set; }
        public string admin_Password { get; set; }
        public string admin_Email { get; set; }
        public string admin_PhoneNum { get; set; }
        public string admin_TrueName { get; set; }
        public string admin_CompanyID { get; set; }
        public int admin_Power { get; set; }
        public string admin_Spare { get; set; }
        public bool admin_IsDel { get; set; }
    
        public virtual company company { get; set; }
    }
}
