//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.admins = new HashSet<admin>();
            this.staffs = new HashSet<staff>();
            this.testInfos = new HashSet<testInfo>();
        }
    
        public string company_Id { get; set; }
        public string company_Name { get; set; }
        public int company_Level { get; set; }
        public string company_Trade { get; set; }
        public string company_Province { get; set; }
        public string company_OwnerCompany { get; set; }
        public bool company_IsSonIn { get; set; }
        public int company_Status { get; set; }
        public string company_Spare { get; set; }
        public bool company_IsDel { get; set; }
    
        public virtual ICollection<admin> admins { get; set; }
        public virtual ICollection<staff> staffs { get; set; }
        public virtual ICollection<testInfo> testInfos { get; set; }
    }
}
