//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class key
    {
        public long key_Id { get; set; }
        public long key_StaffId { get; set; }
        public long key_TestInfoId { get; set; }
        public string key_key1 { get; set; }
        public string key_key2 { get; set; }
        public string key_key3 { get; set; }
        public string key_key4 { get; set; }
        public string key_key5 { get; set; }
        public string key_key6 { get; set; }
        public string key_key7 { get; set; }
        public string key_key8 { get; set; }
        public string key_key9 { get; set; }
        public string key_key10 { get; set; }
        public string key_key11 { get; set; }
        public string key_key12 { get; set; }
        public string key_key13 { get; set; }
        public string key_key14 { get; set; }
        public string key_key15 { get; set; }
        public string key_key16 { get; set; }
        public string key_key17 { get; set; }
        public string key_key18 { get; set; }
        public string key_key19 { get; set; }
        public string key_key20 { get; set; }
        public string key_key21 { get; set; }
        public string key_key22 { get; set; }
        public string key_key23 { get; set; }
        public string key_key24 { get; set; }
        public string key_key25 { get; set; }
        public string key_key26 { get; set; }
        public string key_key27 { get; set; }
        public string key_key28 { get; set; }
        public string key_key29 { get; set; }
        public string key_key30 { get; set; }
        public string key_key31 { get; set; }
        public string key_key32 { get; set; }
        public string key_key33 { get; set; }
        public string key_key34 { get; set; }
        public string key_key35 { get; set; }
        public string key_key36 { get; set; }
        public string key_key37 { get; set; }
        public string key_key38 { get; set; }
        public string key_key39 { get; set; }
        public string key_key40 { get; set; }
        public string key_key41 { get; set; }
        public string key_key42 { get; set; }
        public string key_key43 { get; set; }
        public string key_key44 { get; set; }
        public string key_key45 { get; set; }
        public string key_key46 { get; set; }
        public string key_key47 { get; set; }
        public string key_key48 { get; set; }
        public string key_key49 { get; set; }
        public string key_key50 { get; set; }
        public string key_key51 { get; set; }
        public string key_key52 { get; set; }
        public string key_key53 { get; set; }
        public string key_key54 { get; set; }
        public string key_key55 { get; set; }
        public string key_key56 { get; set; }
        public string key_key57 { get; set; }
        public string key_key58 { get; set; }
        public string key_key59 { get; set; }
        public string key_key60 { get; set; }
        public string key_key61 { get; set; }
        public string key_key62 { get; set; }
        public string key_key63 { get; set; }
        public string key_key64 { get; set; }
        public string key_key65 { get; set; }
        public string key_key66 { get; set; }
        public string key_key67 { get; set; }
        public string key_key68 { get; set; }
        public string key_key69 { get; set; }
        public string key_key70 { get; set; }
        public string key_key71 { get; set; }
        public string key_key72 { get; set; }
        public string key_key73 { get; set; }
        public string key_key74 { get; set; }
        public string key_key75 { get; set; }
        public string key_key76 { get; set; }
        public string key_key77 { get; set; }
        public string key_key78 { get; set; }
        public string key_key79 { get; set; }
        public string key_key80 { get; set; }
        public string key_key81 { get; set; }
        public string key_key82 { get; set; }
        public string key_key83 { get; set; }
        public string key_key84 { get; set; }
        public string key_key85 { get; set; }
        public string key_key86 { get; set; }
        public string key_key87 { get; set; }
        public string key_key88 { get; set; }
        public string key_key89 { get; set; }
        public string key_key90 { get; set; }
        public string key_key91 { get; set; }
        public string key_key92 { get; set; }
        public string key_key93 { get; set; }
        public string key_key94 { get; set; }
        public string key_key95 { get; set; }
        public string key_key96 { get; set; }
        public string key_key97 { get; set; }
        public string key_key98 { get; set; }
        public string key_key99 { get; set; }
        public string key_key100 { get; set; }
        public bool key_IsDel { get; set; }
    
        public virtual staff staff { get; set; }
        public virtual testInfo testInfo { get; set; }
    }
}
