//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        public question()
        {
            this.tests = new HashSet<test>();
        }
    
        public long question_Id { get; set; }
        public string qusetion_Stem { get; set; }
        public string question_Option1 { get; set; }
        public string question_Option2 { get; set; }
        public string question_Option3 { get; set; }
        public string question_Option4 { get; set; }
        public string question_Option5 { get; set; }
        public string question_Option6 { get; set; }
        public string question_Option7 { get; set; }
        public int question_ClassId { get; set; }
        public string question_Spare { get; set; }
        public bool question_IsDel { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual ICollection<test> tests { get; set; }
    }
}
