//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public staff()
        {
            this.keys = new HashSet<key>();
        }
    
        public long staff_Id { get; set; }
        public string staff_Username { get; set; }
        public string staff_Password { get; set; }
        public string staff_OwnCompanyId { get; set; }
        public string staff_Email { get; set; }
        public string staff_TrueName { get; set; }
        public string staff_Department { get; set; }
        public bool staff_IsWrite { get; set; }
        public string staff_Spare { get; set; }
        public bool staff_IsDel { get; set; }
    
        public virtual company company { get; set; }
        public virtual ICollection<key> keys { get; set; }
    }
}
