//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class testInfo
    {
        public testInfo()
        {
            this.keys = new HashSet<key>();
            this.tests = new HashSet<test>();
        }
    
        public long testInfo_Id { get; set; }
        public string testInfo_Name { get; set; }
        public string testInfo_OwnComPanyId { get; set; }
        public System.DateTime testInfo_GenerateTime { get; set; }
        public System.DateTime testInfo_StartTime { get; set; }
        public System.DateTime testInfo_Deadline { get; set; }
        public string testInfo_Spare { get; set; }
        public bool testInfo_IsDel { get; set; }
    
        public virtual company company { get; set; }
        public virtual ICollection<key> keys { get; set; }
        public virtual ICollection<test> tests { get; set; }
    }
}
